title: Bounce Security Consulting
description: Efficient, Value-Driven Security

defaults:
  -
    scope:
      path: "" 
    values:
      layout: "default"
      
kramdown: 
  parse_block_html : true
  parse_span_html  : true
